export const careTheme = {
    colors: {
        primary: '#C24A3A',
        secondary: '#236CA4',
        accent: '#F2BFB0',
        background: '#F2F0E0',
        text: '#333333',
        muted: '#6b7280',
        headerFrom: '#C24A3A',
        headerTo: '#236CA4',
        headerSolid: '#C24A3A',
        headerStyle: 'solid', // 'gradient' or 'solid'
        footer: '#236CA4',
        heroBackground: '#F2F0E0',
        heroText: '#333333',
        heroAccent: '#C24A3A',
        buttonPrimary: '#C24A3A',
        buttonPrimaryHover: '#a03d30',
        buttonSecondary: '#236CA4',
        buttonSecondaryText: '#FFFFFF',
        buttonSecondaryHover: '#075490',
        success: '#3CB371',
        danger: '#f56c6c',
        warning: '#f6ab4a',
        info: '#63b3ed',
    },
    fonts: {
        sans: '"Albert Sans", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
        serif: 'Castoro, ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        heading: '"Albert Sans", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFile, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    },
};
