export const customTheme = {
    colors: {
        primary: '#3A506B',
        secondary: '#5BC0BE',
        accent: '#FFA62B',
        background: '#F5F5F5',
        text: '#1C2541',
        muted: '#6B7280',
        headerFrom: '#3A506B',
        headerTo: '#5BC0BE',
        headerSolid: '#3A506B',
        headerStyle: 'gradient', // 'gradient' or 'solid'
        footer: '#1C2541',
        heroBackground: '#E9ECEF',
        heroText: '#1C2541',
        heroAccent: '#5BC0BE',
        buttonPrimary: '#3A506B',
        buttonPrimaryHover: '#2C3E50',
        buttonSecondary: '#5BC0BE',
        buttonSecondaryText: '#FFFFFF',
        buttonSecondaryHover: '#45A29E',
        success: '#28A745',
        danger: '#DC3545',
        warning: '#FFC107',
        info: '#17A2B8',
    },
    fonts: {
        sans: '"Poppins", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
        serif: '"Merriweather", ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        heading: '"Poppins", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    },
};
